name: Deploy Static GitHub Pages

on:
  push:
    branches:
      - main # Memicu saat ada push ke cabang 'main'
  
  workflow_dispatch: # Mengizinkan trigger manual

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    # Menggunakan environment 'github-pages' yang merupakan best practice baru
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write # Diperlukan untuk deployment Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # 1. Siapkan Konfigurasi Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 2. Setup Node and install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm intall

      # 3. Build and export static site
      - name: Build
        run: npm run build

      - name: Export static site
        # next export will output static files; write to ./out
        run: npx next export -o out

      # 4. Unggah artefak dari folder 'out'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Mengatur path ke folder output export Next.js
          path: './out'

      # 5. Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
